### ISSUE TITLE
psycopg2 broken in latest infra flavor

### ISSUE THREAD

**Issue by jhosteny** [cytopia/docker-ansible#59]
It looks like one of the recent changes removed libpq:

```bash
docker run --rm -it cytopia/ansible:2.9-infra sh
[INFO] root> sh
/data # python3
Python 3.6.9 (default, Jul 19 2020, 03:46:11) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: Error loading shared library libpq.so.5: No such file or directory (needed by /usr/lib/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so)
>>> 
/data # apk add libpq
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing libpq (11.10-r0)
OK: 103 MiB in 59 packages
/data # python3
Python 3.6.9 (default, Jul 19 2020, 03:46:11) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> 
```

**Comment by cytopia** [comment]
Good catch, fix is on the way
