### ISSUE TITLE
module 'ansible_collections.ansible.builtin.plugins.action' has no attribute 'ActionBase'

### ISSUE THREAD

**Issue by Olegt0rr** [cytopia/docker-ansible#96]
Attached mitogen configuration doesn't works

### Image
cytopia/ansible:2.9-tools

### ansible.cfg
```ini
[defaults]
...
;Run Ansible playbooks with Mitogen
strategy_plugins = /usr/lib/python3.8/site-packages/ansible_mitogen/plugins/strategy
strategy = mitogen_linear
```

### CI output
```
ERROR! Unexpected Exception, this is probably a bug: module 'ansible_collections.ansible.builtin.plugins.action' has no attribute 'ActionBase'
the full traceback was:
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.8/site-packages/ansible/cli/playbook.py", line 128, in run
    results = pbex.run()
  File "/usr/lib/python3.8/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_queue_manager.py", line 261, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/loader.py", line 525, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/ansible_mitogen/plugins/strategy/mitogen_linear.py", line 56, in <module>
    import ansible_mitogen.strategy
  File "/usr/lib/python3.8/site-packages/ansible_mitogen/strategy.py", line 43, in <module>
    import ansible_mitogen.mixins
  File "/usr/lib/python3.8/site-packages/ansible_mitogen/mixins.py", line 78, in <module>
    class ActionModuleMixin(ansible.plugins.action.ActionBase):
AttributeError: module 'ansible_collections.ansible.builtin.plugins.action' has no attribute 'ActionBase'
```

**Comment by cytopia** [comment]
@Olegt0rr thanks for reporting


This appears to be a mitogen issue itself. See here for a bug report on their repository: https://github.com/mitogen-hq/mitogen/issues/652.

The mentioned issue has been closed with a fix for Ansible 2.10+ here: https://github.com/mitogen-hq/mitogen/pull/715

So I guess there is nothing I can do on my project as it is mitogen related.
